export const motivationalQuotes = [
  "The only bad workout is the one that didn't happen.",
  "Your body can stand almost anything. It's your mind you have to convince.",
  "Success is the sum of small efforts repeated day in and day out.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Don't wish for it, work for it.",
  "Progress, not perfection.",
  "Strong is what happens when you run out of weak.",
  "The only way to finish is to start.",
  "A one hour workout is only 4% of your day.",
  "You don't have to be extreme, just consistent.",
  "Your future self will thank you.",
  "Sweat is magic. Cover yourself in it daily to grant your wishes.",
  "Train like a beast, look like a beauty.",
  "The hard days are what make you stronger.",
  "Make yourself proud.",
  "The body achieves what the mind believes.",
  "Stronger than yesterday.",
  "Champions train, losers complain.",
  "You are your only limit.",
  "Exercise is a celebration of what your body can do.",
  "The difference between try and triumph is a little umph.",
  "When you feel like quitting, think about why you started.",
  "Take care of your body. It's the only place you have to live.",
  "Movement is a medicine for creating change in a person's physical, emotional, and mental states.",
  "If it doesn't challenge you, it won't change you.",
  "Fall in love with taking care of yourself.",
  "Fitness is not about being better than someone else, it's about being better than you used to be.",
  "The groundwork for all happiness is good health.",
  "What seems impossible today will one day become your warm-up.",
  "The clock is ticking. Are you becoming the person you want to be?",
  "Your health is an investment, not an expense.",
  "Every workout counts.",
  "Discipline is choosing between what you want now and what you want most.",
  "Your only competition is who you were yesterday.",
  "Strength doesn't come from what you can do, it comes from overcoming the things you once thought you couldn't.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "Exercise should be regarded as a tribute to the heart.",
  "A healthy outside starts from the inside.",
  "Physical fitness is the first requisite of happiness.",
  "The last three or four reps is what makes the muscle grow.",
  "No pain, no gain. Shut up and train.",
  "Once you are exercising regularly, the hardest thing is to stop it.",
  "The reason I exercise is for the quality of life I enjoy.",
  "You're only one workout away from a good mood.",
  "The secret of getting ahead is getting started.",
  "Do something today that your future self will thank you for.",
  "The only person you are destined to become is the person you decide to be.",
  "Those who think they have no time for bodily exercise will sooner or later have to find time for illness.",
  "Fitness is like a relationship. You can't cheat and expect it to work.",
  "Exercise is king. Nutrition is queen. Put them together and you've got a kingdom.",
  "Today I will do what others won't, so tomorrow I can accomplish what others can't.",
  "Push yourself because no one else is going to do it for you.",
  "Your body hears everything your mind says.",
  "If you think lifting is dangerous, try being weak. Being weak is dangerous.",
  "The resistance that you fight physically in the gym and the resistance that you fight in life can only build a strong character.",
  "Most people fail, not because of lack of desire, but because of lack of commitment.",
  "Good things come to those who sweat.",
  "The only place where success comes before work is in the dictionary.",
  "You miss 100% of the workouts you don't do.",
  "Results happen over time, not overnight. Work hard, stay consistent, and be patient.",
  "Don't count the days, make the days count.",
  "All progress takes place outside the comfort zone.",
  "The pain of discipline is far less than the pain of regret.",
  "Whether you think you can or think you can't, you're right.",
  "It's going to be a journey. It's not a sprint to get in shape.",
  "Excuses don't burn calories.",
  "Making excuses burns zero calories per hour.",
  "Strive for progress, not perfection.",
  "Your body is a reflection of your lifestyle.",
  "Every champion was once a contender that refused to give up.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "The hardest lift is lifting your butt off the couch.",
  "Age is no barrier. It's a limitation you put on your mind.",
  "Fitness is not a destination, it is a way of life.",
  "Hustle for that muscle.",
  "Sore today, strong tomorrow.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Don't stop when you're tired. Stop when you're done.",
  "Great things never come from comfort zones.",
  "Doubt kills more dreams than failure ever will.",
  "You are stronger than you think.",
  "Be stronger than your excuses.",
  "The hardest part is showing up.",
  "Train insane or remain the same.",
  "The gym is my therapy.",
  "Hard work beats talent when talent doesn't work hard.",
  "Life begins at the end of your comfort zone.",
  "You don't get what you wish for, you get what you work for.",
  "Pain is temporary, pride is forever.",
  "Obsessed is a word the lazy use to describe the dedicated.",
  "Suffer the pain of discipline or suffer the pain of regret.",
  "Your health account, your bank account, they're the same thing. The more you put in, the more you can take out.",
  "Respect your body. It's the only one you get.",
  "To enjoy the glow of good health, you must exercise.",
  "Today is your opportunity to build the tomorrow you want.",
  "You can feel sore tomorrow or you can feel sorry tomorrow. You choose.",
  "I don't count my sit-ups. I only start counting when it starts hurting.",
  "Strength does not come from the physical capacity. It comes from an indomitable will.",
  "Take care of your body. It's the only place you have to live.",
  "Fitness is like marriage. You can't cheat on it and expect it to work.",
  "The gym is not a place, it's a mindset.",
  "Sweat is just fat crying.",
  "A year from now you'll wish you started today.",
  "Dead last finish is greater than did not finish, which trumps did not start.",
  "We are what we repeatedly do. Excellence then is not an act but a habit.",
  "Take rest. A field that has rested gives a bountiful crop.",
  "The way to get started is to quit talking and begin doing.",
  "You can have results or excuses, not both.",
  "Action is the foundational key to all success.",
  "The question isn't who is going to let me, it's who is going to stop me.",
];

export function getDailyQuote(): string {
  const today = new Date();
  const dayOfYear = Math.floor((today.getTime() - new Date(today.getFullYear(), 0, 0).getTime()) / 86400000);
  const index = dayOfYear % motivationalQuotes.length;
  return motivationalQuotes[index];
}
